services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    image: simple-store-app-flask:latest
    container_name: container-store-app-flask
    restart: on-failure
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
    network_mode: bridge
